name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node Version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: pwd
      - run: ll client/public
      - run: cd client && npm run build
      # - run: npm run build --prefix client